name: clone workflow
on: 
  workflow_dispatch:   
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd ~
              cd ..
              cd pub
              git clone git@github.com:sakethkura/cmsc389T-web-template.git